### ISSUE TITLE
Clear screen just before printing?

### ISSUE THREAD

**Issue by M5oul** [duniter/silkaj#8]
It's annoying to wait for next result as `network` and `issuers n` sub-commands could take a while.
I don't really want to do it because:
- `os.system` is not recommended to use as it call OS commands.
- `os.system("clear")` need to be put before every printing sub-commands against one currently.
- `import os` need to be put on `command.py` and more file if this file will be split.

**Comment by M5oul** [comment]
Finally done. It's more beautiful to see clear then just after printing.

**Comment by mmuman** [comment]
Hmm, using system() to run an external command is quite ugly, and won't work in Windows (cls vs clear). However there doesn't seem to be a clean way without using curses:
http://stackoverflow.com/questions/18937058/python-clear-screen-in-shell
http://stackoverflow.com/questions/517970/how-to-clear-python-interpreter-console
http://stackoverflow.com/questions/2084508/clear-terminal-in-python
